import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import useSWR from 'swr'

import logoS3 from '../../public/logoS3.png';
import logoCF from '../../public/logoCloudFront.png';
import logo from '../../public/logo.svg';

// To be updated with the Amazon CloudFront distribution domain deployed through the CloudFormation Template
// You can view this domain in the 'Output' tab of your CloudFormation stack deployment
const APIEndPoint = 'https://<your-api-domain-name>/v1/hello'

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>

          <p>This react-based single page application (SPA) is hosted in an Amazon S3 bucket exposed through an Amazon CloudFront distribution.</p>
          <p>It calls an API configured in Amazon API Gateway and exposed through the same Amazon CloudFront distribution as the application.</p>
          <img src={logo.src} className={styles.app_mainlogo} alt="logo"/>

          <HelloWorld/>

          <div className={styles.logos}>
            <Image
              className={styles.app_logoR2L}
              src={logoS3}
              alt="Amazon S3 logo"
              priority
            />
            <Image
              className={styles.app_logoL2R}
              src={logoCF}
              alt="Amazon CloudFront logo"
              priority
            />
          </div>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Read Amazon S3 Documentation
            </a>
            <a
              href="https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read Amazon CloudFront Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}

const fetcher = (url:string) => fetch(url).then((res) => res.json());

function HelloWorld() {
  const { data, error } = useSWR(APIEndPoint, fetcher)
 
  if (error) return <div>Failed to call REST API: {error.message}</div>
  if (!data) return <div>Loading...</div>
 
  return (
    <div>{data.message}</div>
  )
}